_target_: gflownet.utils.logger.Logger

do:
  online: False
  times: False

project_name: "GFlowNet"

# Log directory
logdir:
  root: ./logs
  ckpts: ckpts
  overwrite: True

debug: False
lightweight: False
progress: True
context: "0"
notes: null
entity: null