defaults:
  - base

_target_: mvp_simplex_env.SimplexWalker

id: mvp_simplex
continuous: True
# Dimensions of hypercube
n_dim: 4
# Constant to restrict interval of test sets
kappa: 1e-3
# Policy
min_incr: 0.01
n_comp: 2
epsilon: 1e-6
beta_params_min: 0.1
beta_params_max: 100.0
random_distr_params:
  beta_weights: 1.0
  beta_alpha: 10.0
  beta_beta: 10.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
  one_hot_logits: [1.0, 1.0, 1.0, 1.0]

fixed_distr_params:
  beta_weights: 1.0
  beta_alpha: 10.0
  beta_beta: 10.0
  bernoulli_bts_prob: 0.1
  bernoulli_eos_prob: 0.1
  one_hot_logits: [1.0, 1.0, 1.0, 1.0]


buffer:
  #data_path: null
  train: 
    type: csv
    path: ./buffer/states_train_trimmed.csv
    samples_column: samples
    energies_column: energies    

 




